[build]
  command = "echo 'No build command needed'"
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["paradas.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#static"